# Copyright (c) 2026, ERPNext Extensions contributors
"""Historical Stock Integrity & Repair (5.3.0 — Master Plan V2).

Repairs stock truth in this order:

    Stock Entry economic truth
    → SLE
    → forward item/warehouse/batch valuation
    → Bin
    → selective GL (G1–G4 only)
    → Failed RIV retry when the chain is healthy

Never: GL first, Bin first, global RIV, live Bin as rate truth, abs() to hide
invalid valuation, or bulk apply of AMBIGUOUS rows.
"""

from __future__ import annotations

CONFIDENCE_EXACT = "EXACT"
CONFIDENCE_LIKELY = "LIKELY"
CONFIDENCE_AMBIGUOUS = "AMBIGUOUS"
CONFIDENCE_MANUAL = "MANUAL"

TOPIC_POSTING_ORDER = "POSTING_ORDER"
TOPIC_ZERO_RATE = "ZERO_RATE"
TOPIC_WRONG_RATE = "WRONG_RATE"
TOPIC_MANUFACTURE = "MANUFACTURE"
TOPIC_SLE_BIN = "SLE_BIN"
TOPIC_GL = "GL"
TOPIC_FAILED_RIV = "FAILED_RIV"
TOPIC_I4 = "I4_LEFTOVER"
TOPIC_I1 = "I1_NEGATIVE_RATE"
TOPIC_SLE_GL_DRIFT = "SLE_GL_DRIFT"

SLE_GL_DRIFT_REPAIR = "SLE_GL_DRIFT"
READY_GL_ONLY = "READY_GL_ONLY"
NO_DRIFT = "NO_DRIFT"
WAITING_SLE_REPAIR = "WAITING_SLE_REPAIR"
EXPECTED_GL_ERROR = "EXPECTED_GL_ERROR"
UNBALANCED_EXPECTED_GL = "UNBALANCED_EXPECTED_GL"
CONFLICTING_RIV = "CONFLICTING_RIV"
MANUAL_REVIEW = "MANUAL_REVIEW"

I1_NEGATIVE_RATE_REPAIR = "I1_NEGATIVE_RATE_REPAIR"
I1_READY = "READY_I1"
I1_WAITING = "WAITING_I1"
I1_MANUAL = "MANUAL_I1"
I1_REPAIRED = "I1_REPAIRED"
I1_HEALTHY = "HEALTHY"

I4_LEFTOVER_REPAIR = "I4_LEFTOVER_REPAIR"
I4_READY = "READY_I4"
I4_WAITING = "WAITING_I4"
I4_REPLAY_REQUIRED = "I4_REPLAY_REQUIRED"
I4_REPAIRED = "I4_REPAIRED"
I4_HEALTHY = "HEALTHY"

# v5.3.4 — zero valuation provenance (do not collide with Zero Rate Z0–Z4).
TOPIC_LEFTOVER_MA = "LEFTOVER_MA"
LEFTOVER_MA_REPAIR = "LEFTOVER_MA_REPAIR"
LEFTOVER_MA_READY = "READY_LEFTOVER_MA"
LEFTOVER_MA_WAITING = "WAITING_LEFTOVER_MA"
LEFTOVER_MA_MANUAL = "MANUAL_LEFTOVER_MA"
LEFTOVER_MA_REPAIRED = "LEFTOVER_MA_REPAIRED"
LEFTOVER_MA_FAILED_POSTCONDITION = "FAILED_POSTCONDITION"
LEFTOVER_MA_FAILED_RIV = "FAILED_RIV"
LEFTOVER_MA_REPORT_MISMATCH = "FAILED_POSTCONDITION: REPORT_LEDGER_MISMATCH"
ZP_PROVEN_LEGITIMATE_ZERO = "ZP_PROVEN_LEGITIMATE_ZERO"
ZP_VALUED_STOCK_ZERO_STAMP = "ZP_VALUED_STOCK_ZERO_STAMP"
ZP_ZERO_INBOUND_ON_VALUED_POSITION = "ZP_ZERO_INBOUND_ON_VALUED_POSITION"
ZP_DEPLETED_OLD_VALUE_HISTORY = "ZP_DEPLETED_OLD_VALUE_HISTORY"
ZP_UNPROVEN_ZERO = "ZP_UNPROVEN_ZERO"

Z0_LEGITIMATE_ZERO = "Z0_LEGITIMATE_ZERO"
Z0_LEGITIMATE_SCRAP_ZERO = "LEGITIMATE_SCRAP_ZERO_RATE"  # legacy label; scrap WH alone is not NO_ACTION
Z1_HISTORICAL_RATE_LOST = "Z1_HISTORICAL_RATE_LOST"
Z2_RIV_REWRITE = "Z2_RIV_REWRITE"
Z3_MISSING_INCOMING_VALUATION = "Z3_MISSING_INCOMING_VALUATION"
Z4_BATCH_SABB_LOOKUP_ZERO = "Z4_BATCH_SABB_LOOKUP_ZERO"
Z5_IRAN_ALIGNMENT = "Z5_IRAN_ALIGNMENT"
Z6_UNKNOWN = "Z6_UNKNOWN"
# v5.3.0 purpose-first: Material Receipt without authoritative source → user review.
Z_MATERIAL_RECEIPT_USER_REVIEW = "MATERIAL_RECEIPT_ZERO_RATE_USER_REVIEW"
STATUS_MATERIAL_RECEIPT_USER_REVIEW = "MATERIAL_RECEIPT_ZERO_RATE_USER_REVIEW"
NO_AUTHORITATIVE_SOURCE = "NO_AUTHORITATIVE_SOURCE"
AUTHORITATIVE_SOURCE_EXISTS_BUT_RATE_IS_ZERO = "AUTHORITATIVE_SOURCE_EXISTS_BUT_RATE_IS_ZERO"

# Rule 6 — precise zero-rate reasons (prefer these over generic ZERO_RATE).
ZERO_REASON_LEGITIMATE_SCRAP = "LEGITIMATE_SCRAP_ZERO_RATE"
ZERO_REASON_TRUE_CORRUPTION = "TRUE_ZERO_RATE_CORRUPTION"
ZERO_REASON_MISSING_SOURCE = "MISSING_SOURCE_RATE"
ZERO_REASON_NO_AUTHORITATIVE_SOURCE = "NO_AUTHORITATIVE_SOURCE"
ZERO_REASON_UPSTREAM_POISONED = "UPSTREAM_POISONED"
ZERO_REASON_MANUFACTURE_DEP = "MANUFACTURE_DEPENDENCY"
ZERO_REASON_POSTING_ORDER_DEP = "POSTING_ORDER_DEPENDENCY"
ZERO_REASON_CONVERSION = "CONVERSION_ARTIFACT"
ZERO_REASON_MANUAL = "MANUAL_REVIEW"
ZERO_REASON_MATERIAL_RECEIPT_USER = "MATERIAL_RECEIPT_ZERO_RATE_USER_REVIEW"

NO_ACTION_REQUIRED = "NO_ACTION_REQUIRED"
MATCHED_BUT_CORRUPT = "MATCHED_BUT_CORRUPT"
ZERO_QTY_NONZERO_VALUE = "ZERO_QTY_NONZERO_VALUE"

W_ZERO_BASIC = "ZERO_BASIC_RATE"
W_WRONG_BASIC = "WRONG_BASIC_RATE"
W_WRONG_VALUATION = "WRONG_VALUATION_RATE"
W_WRONG_INCOMING = "WRONG_INCOMING_RATE"
W_WRONG_OUTGOING = "WRONG_OUTGOING_RATE"
W_WRONG_AVG = "WRONG_AVG_RATE"
W_WRONG_AMOUNT = "WRONG_AMOUNT"
W_WRONG_SVD = "WRONG_STOCK_VALUE_DIFFERENCE"
W_STALE_SOURCE = "WRONG_VS_RECONSTRUCTED_SOURCE"

RECONSTRUCTION_PRIORITY = (
	"version",
	"previous_healthy_sle",
	"batch_inward",
	"transfer_source",
	"implied_svd",
	"manufacture_pool",
	"purchase_receipt",
	"stock_reconciliation",
	"moving_average",
	"manual",
)

STATUS_RECONSTRUCTABLE = "RECONSTRUCTABLE"
STATUS_DEPENDENCY_REPAIR_REQUIRED = "DEPENDENCY_REPAIR_REQUIRED"
STATUS_VALUATION_POISON_DEPENDENCY = "VALUATION_POISON_DEPENDENCY"
STATUS_MANUAL_REVIEW = "MANUAL_REVIEW"
STATUS_DRY_RUN = "DRY_RUN"
STATUS_REPAIRED = "REPAIRED"
STATUS_BLOCKED = "BLOCKED"
STATUS_ORDER_FIXED_RATE_REBUILD_REQUIRED = "ORDER_FIXED_RATE_REBUILD_REQUIRED"
STATUS_RATE_REBUILD_COMPLETE = "RATE_REBUILD_COMPLETE"
STATUS_INTEGRITY_COMPLETE = "INTEGRITY_COMPLETE"
STATUS_DOWNSTREAM_PENDING = "DOWNSTREAM_PENDING"
STATUS_DOWNSTREAM_REPLAY_REQUIRED = "DOWNSTREAM_REPLAY_REQUIRED"
STATUS_DOWNSTREAM_REPLAYING = "DOWNSTREAM_REPLAYING"
STATUS_DOWNSTREAM_COMPLETE = "DOWNSTREAM_COMPLETE"
STATUS_DOWNSTREAM_SKIPPED = "DOWNSTREAM_SKIPPED"
STATUS_SAFE_TO_REPOST = "SAFE_TO_REPOST"
STATUS_UNSAFE_TO_REPOST = "UNSAFE_TO_REPOST"

G0_HEALTHY = "G0_HEALTHY"
G1_ECONOMICALLY_WRONG = "G1_BALANCED_BUT_ECONOMICALLY_WRONG"
G2_MISSING = "G2_MISSING"
G3_UNBALANCED = "G3_UNBALANCED"
G4_POISONED_SLE = "G4_BUILT_FROM_POISONED_SLE"

SLE_HEALTHY = "HEALTHY"
SLE_REPLAY_REQUIRED = "REPLAY_REQUIRED"
SLE_PATIENT_ZERO_REQUIRED = "PATIENT_ZERO_REQUIRED"
SLE_POISONED_CHAIN = "POISONED_CHAIN"
SLE_AMBIGUOUS = "AMBIGUOUS"
SLE_WAITING_DOWNSTREAM_REPAIR = "WAITING_DOWNSTREAM_REPAIR"

RIV_WAITING_RATE = "WAITING_RATE"
RIV_WAITING_SLE = "WAITING_SLE"
RIV_WAITING_GL = "WAITING_GL"
RIV_WAITING_PATIENT_ZERO = "WAITING_PATIENT_ZERO"
RIV_WAITING_REPLAY = "WAITING_REPLAY"
RIV_SAFE_TO_RETRY = "SAFE_TO_RETRY"
RIV_NEGATIVE_STOCK = "NEGATIVE_STOCK"
RIV_RAW_MATERIAL_COST = "RAW_MATERIAL_COST"
RIV_VALUATION_INTEGRITY = "VALUATION_INTEGRITY"
RIV_DEADLOCK = "DEADLOCK"
RIV_TIMEOUT = "TIMEOUT"
RIV_UNKNOWN = "UNKNOWN"
RIV_PERMANENTLY_UNSAFE = "PERMANENTLY_UNSAFE"
# Back-compat aliases used by older scans
RIV_UNSAFE = RIV_PERMANENTLY_UNSAFE
RIV_WAITING_FOR_RATE_REPAIR = "WAITING_FOR_RATE_REPAIR"
RIV_WAITING_FOR_SLE_REPAIR = "WAITING_FOR_SLE_REPAIR"
RIV_WAITING_FOR_GL_REPAIR = "WAITING_FOR_GL_REPAIR"

# Phase 2 GL classifier extensions
GL_ROOT = "GL_ROOT"
GL_DOWNSTREAM = "GL_DOWNSTREAM"
GL_WAITING_SLE = "WAITING_SLE"
GL_WAITING_RATE = "WAITING_RATE"
GL_WAITING_REPLAY = "WAITING_REPLAY"
GL_MANUAL = "MANUAL_GL"


SKIP_LOST_RATE_GUARD = "skip_lost_rate_guard"
HISTORICAL_REPAIR_FLAG = "historical_stock_repair"

RATE_EPS = 0.0001
VALUE_EPS = 0.5
QTY_EPS = 0.0001
POISON_RATE = 1e12
