# Copyright (c) 2026, ERPNext Extensions contributors
"""Historical Stock Integrity & Repair (5.2.7).

Repairs stock truth in this order:

    Stock Entry economic truth
    → SLE
    → forward item/warehouse/batch valuation
    → Bin
    → selective GL (G1–G4 only)
    → Failed RIV retry when the chain is healthy

Never: GL first, Bin first, global RIV, live Bin as rate truth, abs() to hide
invalid valuation, or bulk apply of AMBIGUOUS rows.
"""

from __future__ import annotations

CONFIDENCE_EXACT = "EXACT"
CONFIDENCE_LIKELY = "LIKELY"
CONFIDENCE_AMBIGUOUS = "AMBIGUOUS"

TOPIC_POSTING_ORDER = "POSTING_ORDER"
TOPIC_ZERO_RATE = "ZERO_RATE"
TOPIC_MANUFACTURE = "MANUFACTURE"
TOPIC_SLE_BIN = "SLE_BIN"
TOPIC_GL = "GL"
TOPIC_FAILED_RIV = "FAILED_RIV"

Z0_LEGITIMATE_ZERO = "Z0_LEGITIMATE_ZERO"
Z1_HISTORICAL_RATE_LOST = "Z1_HISTORICAL_RATE_LOST"
Z2_RIV_REWRITE = "Z2_RIV_REWRITE"
Z3_MISSING_INCOMING_VALUATION = "Z3_MISSING_INCOMING_VALUATION"
Z4_BATCH_SABB_LOOKUP_ZERO = "Z4_BATCH_SABB_LOOKUP_ZERO"
Z5_IRAN_ALIGNMENT = "Z5_IRAN_ALIGNMENT"
Z6_UNKNOWN = "Z6_UNKNOWN"

STATUS_RECONSTRUCTABLE = "RECONSTRUCTABLE"
STATUS_DEPENDENCY_REPAIR_REQUIRED = "DEPENDENCY_REPAIR_REQUIRED"
STATUS_VALUATION_POISON_DEPENDENCY = "VALUATION_POISON_DEPENDENCY"
STATUS_MANUAL_REVIEW = "MANUAL_REVIEW"
STATUS_DRY_RUN = "DRY_RUN"
STATUS_REPAIRED = "REPAIRED"
STATUS_BLOCKED = "BLOCKED"
STATUS_SAFE_TO_REPOST = "SAFE_TO_REPOST"
STATUS_UNSAFE_TO_REPOST = "UNSAFE_TO_REPOST"

G0_HEALTHY = "G0_HEALTHY"
G1_ECONOMICALLY_WRONG = "G1_BALANCED_BUT_ECONOMICALLY_WRONG"
G2_MISSING = "G2_MISSING"
G3_UNBALANCED = "G3_UNBALANCED"
G4_POISONED_SLE = "G4_BUILT_FROM_POISONED_SLE"

SLE_HEALTHY = "HEALTHY"
SLE_REPLAY_REQUIRED = "REPLAY_REQUIRED"
SLE_PATIENT_ZERO_REQUIRED = "PATIENT_ZERO_REQUIRED"
SLE_POISONED_CHAIN = "POISONED_CHAIN"
SLE_AMBIGUOUS = "AMBIGUOUS"

RIV_WAITING_RATE = "WAITING_FOR_RATE_REPAIR"
RIV_WAITING_SLE = "WAITING_FOR_SLE_REPAIR"
RIV_WAITING_GL = "WAITING_FOR_GL_REPAIR"
RIV_SAFE_TO_RETRY = "SAFE_TO_RETRY"
RIV_UNSAFE = "UNSAFE"

SKIP_LOST_RATE_GUARD = "skip_lost_rate_guard"
HISTORICAL_REPAIR_FLAG = "historical_stock_repair"

RATE_EPS = 0.0001
VALUE_EPS = 0.5
QTY_EPS = 0.0001
POISON_RATE = 1e12
