# Copyright (c) 2026, ERPNext Extensions contributors
"""Deterministic status codes for Job Card Stock Rebuild (v5.4.1 Phase 1)."""

from __future__ import annotations

BALANCED = "BALANCED"
JOB_CARD_TRACKING_INCOMPLETE = "JOB_CARD_TRACKING_INCOMPLETE"
MISSING_MANUFACTURE_CONSUMPTION = "MISSING_MANUFACTURE_CONSUMPTION"
PARTIAL_MANUFACTURE_CONSUMPTION = "PARTIAL_MANUFACTURE_CONSUMPTION"
OVER_CONSUMED = "OVER_CONSUMED"
RETURN_MISMATCH = "RETURN_MISMATCH"
COMPONENT_SCRAP_MISMATCH = "COMPONENT_SCRAP_MISMATCH"
SECONDARY_ITEM_MISMATCH = "SECONDARY_ITEM_MISMATCH"
BATCH_MISMATCH = "BATCH_MISMATCH"
UOM_MAPPING_REQUIRED = "UOM_MAPPING_REQUIRED"
AMBIGUOUS_OWNERSHIP = "AMBIGUOUS_OWNERSHIP"
ORPHAN_WIP = "ORPHAN_WIP"
POSTING_ORDER_WARNING = "POSTING_ORDER_WARNING"
STALE_PREVIEW = "STALE_PREVIEW"
DOWNSTREAM_MANUFACTURE_BLOCKED = "DOWNSTREAM_MANUFACTURE_BLOCKED"
MANUAL_REVIEW = "MANUAL_REVIEW"
REBUILD_READY = "REBUILD_READY"
REBUILT = "REBUILT"
NO_CHANGE = "NO_CHANGE"

# Apply blockers (any of these → APPLY disabled)
APPLY_BLOCKERS = frozenset(
	{
		AMBIGUOUS_OWNERSHIP,
		BATCH_MISMATCH,
		UOM_MAPPING_REQUIRED,
		STALE_PREVIEW,
		DOWNSTREAM_MANUFACTURE_BLOCKED,
		MANUAL_REVIEW,
		OVER_CONSUMED,
		RETURN_MISMATCH,
		COMPONENT_SCRAP_MISMATCH,
		SECONDARY_ITEM_MISMATCH,
	}
)

# Warnings that allow tracking rebuild but flag Manufacture Phase 2
WARNINGS_ALLOW_REBUILD = frozenset({POSTING_ORDER_WARNING})

__all__ = [
	"BALANCED",
	"JOB_CARD_TRACKING_INCOMPLETE",
	"MISSING_MANUFACTURE_CONSUMPTION",
	"PARTIAL_MANUFACTURE_CONSUMPTION",
	"OVER_CONSUMED",
	"RETURN_MISMATCH",
	"COMPONENT_SCRAP_MISMATCH",
	"SECONDARY_ITEM_MISMATCH",
	"BATCH_MISMATCH",
	"UOM_MAPPING_REQUIRED",
	"AMBIGUOUS_OWNERSHIP",
	"ORPHAN_WIP",
	"POSTING_ORDER_WARNING",
	"STALE_PREVIEW",
	"DOWNSTREAM_MANUFACTURE_BLOCKED",
	"MANUAL_REVIEW",
	"REBUILD_READY",
	"REBUILT",
	"NO_CHANGE",
	"APPLY_BLOCKERS",
	"WARNINGS_ALLOW_REBUILD",
]
