# Copyright (c) 2026, ERPNext Extensions contributors
"""Deterministic status codes for Job Card Stock Rebuild (v5.4.1)."""

from __future__ import annotations

BALANCED = "BALANCED"
JOB_CARD_TRACKING_INCOMPLETE = "JOB_CARD_TRACKING_INCOMPLETE"
MISSING_MANUFACTURE_CONSUMPTION = "MISSING_MANUFACTURE_CONSUMPTION"
PARTIAL_MANUFACTURE_CONSUMPTION = "PARTIAL_MANUFACTURE_CONSUMPTION"
OVER_CONSUMED = "OVER_CONSUMED"
RETURN_MISMATCH = "RETURN_MISMATCH"
COMPONENT_SCRAP_MISMATCH = "COMPONENT_SCRAP_MISMATCH"
SECONDARY_ITEM_MISMATCH = "SECONDARY_ITEM_MISMATCH"
BATCH_MISMATCH = "BATCH_MISMATCH"
UOM_MAPPING_REQUIRED = "UOM_MAPPING_REQUIRED"
AMBIGUOUS_OWNERSHIP = "AMBIGUOUS_OWNERSHIP"
ORPHAN_WIP = "ORPHAN_WIP"
POSTING_ORDER_WARNING = "POSTING_ORDER_WARNING"
STALE_PREVIEW = "STALE_PREVIEW"
DOWNSTREAM_MANUFACTURE_BLOCKED = "DOWNSTREAM_MANUFACTURE_BLOCKED"
MANUAL_REVIEW = "MANUAL_REVIEW"
REBUILD_READY = "REBUILD_READY"
REBUILT = "REBUILT"
NO_CHANGE = "NO_CHANGE"
TYPE_CHANGE_SUGGESTED = "TYPE_CHANGE_SUGGESTED"
TYPE_CHANGE_APPROVED = "TYPE_CHANGE_APPROVED"
MANUFACTURE_READINESS_PASS = "MANUFACTURE_READINESS_PASS"
MANUFACTURE_READINESS_BLOCKED = "MANUFACTURE_READINESS_BLOCKED"

# Hard Apply blockers for selected JC dependency-unsafe conditions.
# DOWNSTREAM_MANUFACTURE_BLOCKED is a readiness status — Apply of approved
# type corrections may proceed and must re-verify readiness after mutation.
APPLY_BLOCKERS = frozenset(
	{
		AMBIGUOUS_OWNERSHIP,
		BATCH_MISMATCH,
		UOM_MAPPING_REQUIRED,
		STALE_PREVIEW,
		OVER_CONSUMED,
		RETURN_MISMATCH,
		COMPONENT_SCRAP_MISMATCH,
		SECONDARY_ITEM_MISMATCH,
	}
)

# Row-level / informational — do not auto-escalate alone
WARNINGS_ALLOW_REBUILD = frozenset(
	{
		POSTING_ORDER_WARNING,
		MISSING_MANUFACTURE_CONSUMPTION,
		PARTIAL_MANUFACTURE_CONSUMPTION,
		TYPE_CHANGE_SUGGESTED,
		DOWNSTREAM_MANUFACTURE_BLOCKED,
		MANUFACTURE_READINESS_BLOCKED,
		MANUAL_REVIEW,  # row-level unless escalated by service
	}
)

__all__ = [
	"BALANCED",
	"JOB_CARD_TRACKING_INCOMPLETE",
	"MISSING_MANUFACTURE_CONSUMPTION",
	"PARTIAL_MANUFACTURE_CONSUMPTION",
	"OVER_CONSUMED",
	"RETURN_MISMATCH",
	"COMPONENT_SCRAP_MISMATCH",
	"SECONDARY_ITEM_MISMATCH",
	"BATCH_MISMATCH",
	"UOM_MAPPING_REQUIRED",
	"AMBIGUOUS_OWNERSHIP",
	"ORPHAN_WIP",
	"POSTING_ORDER_WARNING",
	"STALE_PREVIEW",
	"DOWNSTREAM_MANUFACTURE_BLOCKED",
	"MANUAL_REVIEW",
	"REBUILD_READY",
	"REBUILT",
	"NO_CHANGE",
	"TYPE_CHANGE_SUGGESTED",
	"TYPE_CHANGE_APPROVED",
	"MANUFACTURE_READINESS_PASS",
	"MANUFACTURE_READINESS_BLOCKED",
	"APPLY_BLOCKERS",
	"WARNINGS_ALLOW_REBUILD",
]
