# Copyright (c) 2026, ERPNext Extensions contributors
"""Phase 2 Wrong Rate Engine — classifier, planner states, controlled apply."""

from __future__ import annotations

# Planner states (no generic BLOCKED)
READY_WRONG_RATE = "READY_WRONG_RATE"
WAITING_RATE_DEPENDENCY = "WAITING_RATE_DEPENDENCY"
WAITING_PATIENT_ZERO = "WAITING_PATIENT_ZERO"
RATE_REPLAY_REQUIRED = "RATE_REPLAY_REQUIRED"
RATE_REPAIR_COMPLETE = "RATE_REPAIR_COMPLETE"
RATE_AMBIGUOUS = "RATE_AMBIGUOUS"
RATE_MANUAL = "RATE_MANUAL"
RATE_POISONED_OPENING = "RATE_POISONED_OPENING"
RATE_WAREHOUSE_ESCALATION = "RATE_WAREHOUSE_ESCALATION"

# Taxonomy buckets
WRONG_BASIC_RATE = "WRONG_BASIC_RATE"
WRONG_VALUATION_RATE = "WRONG_VALUATION_RATE"
WRONG_INCOMING_RATE = "WRONG_INCOMING_RATE"
WRONG_OUTGOING_RATE = "WRONG_OUTGOING_RATE"
WRONG_AMOUNT = "WRONG_AMOUNT"
WRONG_SVD = "WRONG_SVD"
WRONG_SABB_RATE = "WRONG_SABB_RATE"
WRONG_TRANSFER_DEST_RATE = "WRONG_TRANSFER_DEST_RATE"
WRONG_MANUFACTURE_FG_RATE = "WRONG_MANUFACTURE_FG_RATE"
WRONG_COMPONENT_SCRAP_RATE = "WRONG_COMPONENT_SCRAP_RATE"
WRONG_BYPRODUCT_RATE = "WRONG_BYPRODUCT_RATE"
WRONG_MOVING_AVERAGE = "WRONG_MOVING_AVERAGE"
DOWNSTREAM_RATE_SYMPTOM = "DOWNSTREAM_RATE_SYMPTOM"
PATIENT_ZERO_RATE = "PATIENT_ZERO_RATE"
AMBIGUOUS_RATE = "AMBIGUOUS_RATE"
MANUAL_RATE = "MANUAL_RATE"

FLAG_TO_BUCKET = {
	"ZERO_BASIC_RATE": WRONG_BASIC_RATE,
	"WRONG_BASIC_RATE": WRONG_BASIC_RATE,
	"WRONG_VALUATION_RATE": WRONG_VALUATION_RATE,
	"WRONG_INCOMING_RATE": WRONG_INCOMING_RATE,
	"WRONG_OUTGOING_RATE": WRONG_OUTGOING_RATE,
	"WRONG_AMOUNT": WRONG_AMOUNT,
	"WRONG_STOCK_VALUE_DIFFERENCE": WRONG_SVD,
	"WRONG_AVG_RATE": WRONG_MOVING_AVERAGE,
	"WRONG_VS_RECONSTRUCTED_SOURCE": PATIENT_ZERO_RATE,
}
