# Copyright (c) 2026, ERPNext Extensions contributors
"""Warehouse Engine — smallest-safe Item+Warehouse valuation replay.

ERPNext SLE identity is Item + Warehouse. Batch/SABB is supporting metadata.
Escalate LOCAL → BATCH → WO → IDENTITY → WAREHOUSE only when simulation proves
cross-batch MA rewrite is required. Never invent a new valuation algorithm —
reuse ``replay_series`` / posting-order primitives.
"""

from __future__ import annotations

# Scope ladder (smallest first)
SCOPE_LOCAL_VOUCHER = "LOCAL_VOUCHER"
SCOPE_BATCH_SCOPED = "BATCH_SCOPED"
SCOPE_WORK_ORDER_SCOPED = "WORK_ORDER_SCOPED"
SCOPE_IDENTITY_SCOPED = "IDENTITY_SCOPED"
SCOPE_WAREHOUSE_VALUATION = "WAREHOUSE_VALUATION_SCOPED"
SCOPE_UNSAFE_GLOBAL = "UNSAFE_GLOBAL_DEPENDENCY"

# Planner states
READY_WAREHOUSE_REPLAY = "READY_WAREHOUSE_REPLAY"
READY_WAREHOUSE_CAMPAIGN = "READY_WAREHOUSE_CAMPAIGN"
WAITING_WAREHOUSE_DEPENDENCY = "WAITING_WAREHOUSE_DEPENDENCY"
WAITING_WAREHOUSE_CAMPAIGN = "WAITING_WAREHOUSE_CAMPAIGN"
WAREHOUSE_REPLAY_REQUIRED = "WAREHOUSE_REPLAY_REQUIRED"
WAREHOUSE_CAMPAIGN_REQUIRED = "WAREHOUSE_CAMPAIGN_REQUIRED"
WAREHOUSE_REPLAY_COMPLETE = "WAREHOUSE_REPLAY_COMPLETE"
WAREHOUSE_CAMPAIGN_COMPLETE = "WAREHOUSE_CAMPAIGN_COMPLETE"
WAREHOUSE_REAL_SHORTAGE = "WAREHOUSE_REAL_SHORTAGE"
WAREHOUSE_POISONED_OPENING = "WAREHOUSE_POISONED_OPENING"
WAREHOUSE_AMBIGUOUS = "WAREHOUSE_AMBIGUOUS"
UNSAFE_GLOBAL_DEPENDENCY = "UNSAFE_GLOBAL_DEPENDENCY"
UNSAFE_CROSS_IDENTITY = "UNSAFE_CROSS_IDENTITY"

SCOPE_ORDER = (
	SCOPE_LOCAL_VOUCHER,
	SCOPE_BATCH_SCOPED,
	SCOPE_WORK_ORDER_SCOPED,
	SCOPE_IDENTITY_SCOPED,
	SCOPE_WAREHOUSE_VALUATION,
	SCOPE_UNSAFE_GLOBAL,
)
