# Copyright (c) 2026, ERPNext Extensions contributors
"""v4.7.2: flag on Batch for placeholder lots created by Daily Production Log (idempotent)."""

from __future__ import annotations

import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields


def execute():
	if not frappe.db.exists("DocType", "Batch"):
		return
	create_custom_fields(
		{
			"Batch": [
				{
					"fieldname": "custom_is_placeholder_lot",
					"label": "Placeholder Lot (Daily Production)",
					"fieldtype": "Check",
					"insert_after": "custom_batch_no"
					if frappe.get_meta("Batch").has_field("custom_batch_no")
					else "batch_id",
					"read_only": 1,
					"description": "Lot number was generated by Daily Production Log with a placeholder sub-lot suffix (-Lnn).",
				}
			]
		},
		ignore_validate=True,
	)
