# Copyright (c) 2026, ERPNext Extensions contributors
"""Strict production dependency edges (EXACT / LIKELY / AMBIGUOUS).

Auto-repair uses EXACT only. LIKELY is preview/manual. AMBIGUOUS fails closed.

An edge A → B exists only when stock generated by A is a structural
prerequisite for B. Same item + same second + same warehouse is not enough.
"""

from __future__ import annotations

from typing import Any

from erpnext_extensions.iran_accounting.stock_posting_order import (
	CONFIDENCE_AMBIGUOUS,
	CONFIDENCE_EXACT,
	CONFIDENCE_LIKELY,
	DEPENDENT_PURPOSES,
	PREREQUISITE_PURPOSES,
)

PRODUCTION_TRANSFER_PURPOSES = {
	"Material Transfer for Manufacture",
	"Material Transfer",
}
PRODUCTION_CONSUME_PURPOSES = {
	"Manufacture",
	"Material Consumption for Manufacture",
	"Material Issue",
	"Material Transfer for Manufacture",
	"Material Transfer",
}


def _g(row: Any, key: str, default=None):
	if row is None:
		return default
	if isinstance(row, dict):
		return row.get(key, default)
	return getattr(row, key, default)


def stock_key(item_code, warehouse, batch_no=None, serial_and_batch_bundle=None) -> tuple:
	batch = (batch_no or "").strip()
	sabb = (serial_and_batch_bundle or "").strip()
	return (item_code or "", warehouse or "", batch, sabb)


def same_stock_identity(a: Any, b: Any) -> bool:
	"""Item + warehouse + batch/SABB. Different warehouse or batch is not a pair."""
	if _g(a, "item_code") != _g(b, "item_code"):
		return False
	if _g(a, "warehouse") != _g(b, "warehouse"):
		return False
	a_batch = (_g(a, "batch_no") or "").strip()
	b_batch = (_g(b, "batch_no") or "").strip()
	if a_batch or b_batch:
		return a_batch == b_batch
	a_sabb = (_g(a, "serial_and_batch_bundle") or "").strip()
	b_sabb = (_g(b, "serial_and_batch_bundle") or "").strip()
	if a_sabb and b_sabb:
		return False
	return True


def classify_edge(
	inbound: dict,
	outbound: dict,
	*,
	same_work_order: bool,
	same_job_card: bool,
	against_stock_entry: bool,
	same_batch: bool,
	inbound_purpose: str | None,
	outbound_purpose: str | None,
) -> tuple[str, str]:
	"""Return (confidence, reason). Fail closed on ambiguity."""
	if not inbound or not outbound:
		return CONFIDENCE_AMBIGUOUS, "missing_document"
	if _g(inbound, "item_code") != _g(outbound, "item_code"):
		return CONFIDENCE_AMBIGUOUS, "different_item"
	if _g(inbound, "warehouse") != _g(outbound, "warehouse"):
		return CONFIDENCE_AMBIGUOUS, "different_warehouse"
	in_batch = (_g(inbound, "batch_no") or "").strip()
	out_batch = (_g(outbound, "batch_no") or "").strip()
	if in_batch and out_batch and in_batch != out_batch:
		return CONFIDENCE_AMBIGUOUS, "different_batch"

	in_p = inbound_purpose or ""
	out_p = outbound_purpose or ""
	structural = same_job_card or against_stock_entry

	reason_parts = []
	if same_job_card:
		reason_parts.append("same_job_card")
	if same_work_order:
		reason_parts.append("same_work_order")
	if against_stock_entry:
		reason_parts.append("against_stock_entry")
	if same_batch and (in_batch or out_batch):
		reason_parts.append("same_batch")
	if in_p == "Material Transfer for Manufacture" and out_p in (
		"Manufacture",
		"Material Consumption for Manufacture",
	):
		reason_parts.append("mtfm_then_consume")
	if in_p == "Manufacture" and out_p in PRODUCTION_CONSUME_PURPOSES:
		reason_parts.append("sfg_then_consume")
	if in_p == "Material Transfer" and out_p in PRODUCTION_CONSUME_PURPOSES:
		reason_parts.append("transfer_then_issue")
	reason = "+".join(reason_parts) or "unproven"

	if structural and in_p in PREREQUISITE_PURPOSES and out_p in DEPENDENT_PURPOSES:
		return CONFIDENCE_EXACT, reason or "linked_production"
	if same_work_order and in_p == "Material Transfer for Manufacture" and out_p in (
		"Manufacture",
		"Material Consumption for Manufacture",
	):
		return CONFIDENCE_EXACT, reason or "wo_mtfm_consume"
	if same_work_order and in_p == "Manufacture" and out_p in PRODUCTION_CONSUME_PURPOSES and same_batch:
		return CONFIDENCE_EXACT, reason or "wo_sfg_consume"

	if same_work_order and in_p in PREREQUISITE_PURPOSES and out_p in DEPENDENT_PURPOSES:
		return CONFIDENCE_LIKELY, reason or "same_work_order_unbatched"
	if same_batch and in_p in PREREQUISITE_PURPOSES and out_p in DEPENDENT_PURPOSES:
		return CONFIDENCE_LIKELY, reason or "same_batch_cross_document"

	return CONFIDENCE_AMBIGUOUS, reason


def is_inbound_sle(actual_qty) -> bool:
	return float(actual_qty or 0) > 0


def is_outbound_sle(actual_qty) -> bool:
	return float(actual_qty or 0) < 0
